apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: test20240421
    name: springboot-helloworld
    labels:
      app: springboot-helloworld
spec:
    replicas: 2
    selector:
      matchLabels:
        app: springboot-helloworld
    template:
      metadata:
        labels:
          app: springboot-helloworld
      spec:
        container:
        - name: pipeline
          image: 192.168.56.102:5100/p_pub/springboot-helloworld:v1.1.93
          imagePullPolicy: Always
          ports:
          - container: 10090
---
apiVersion: v1
kind: Service
metadata:
  namespace: test20240421
  labels:
    app: springboot-helloworld
  name: springboot-helloworld
spec:
  selector:
    app: springboot-helloworld
  ports:
  - port: 11090
    targetPort: 10090
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: test20240421
  name: springboot-helloworld
spec:
  ingressClassName: ingress20240421
  rules:
  - host: fernando.iceworld.pr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: springboot-helloworld
            port:
              number: 11090

