apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test20240421
  name: springboot-helloworld
  labels:
    app: springboot-helloworld-label
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-helloworld-label
  # 元数据，开始定义pod
  template:
    metadata:
      # 此位置必须填写的是pod资源的label
      labels:
        app: springboot-helloworld-label
    spec:
      containers:
      - name: springboot-helloworld-container
        image: 192.168.56.102:5100/p_pub/springboot-helloworld:v1.1.97
        imagePullPolicy: Always
        ports:
        - containerPort: 10090
---
apiVersion: v1
kind: Service
metadata:
  namespace: test20240421
  name: springboot-helloworld-svc
  labels:
    app: springboot-helloworld-svc-label
spec:
  # 标签选择器，选择要跟那个pod资源进行绑定，是pod资源label名称
  selector:
    app: springboot-helloworld-label
  ports:
  - port: 11090
    targetPort: 10090
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: test20240421
  name: springboot-helloworld-ing
spec:
  ingressClassName: ingress20240421
  rules:
  - host: fernando.iceworld.pr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: springboot-helloworld-svc
            port:
              number: 11090

